#Database
POSTGRES_SQL_USERNAME: morgan
POSTGRES_SQL_PASSWORD: morgan
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: bookstore

#Server
SERVER_PORT: 8080
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: localhost
EMAIL_PORT: 1025
EMAIL_ID: morgan@gmail.com
EMAIL_PASSWORD: morgan
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}